// client/src/components/NavBar.vue
<script setup lang="ts">
import { ref } from 'vue';
import { RouterLink } from 'vue-router';
import LoginBadge from './LoginBadge.vue';
import FlyoutPanel from './FlyoutPanel.vue';
import ShoppingCart from './ShoppingCart.vue';
import { count as cartCount } from "@/model/shoppingCart";

const isActive = ref(false);
const isShoppingCartOpen = ref(false);

</script>

<template>
  <nav class="navbar" role="navigation" aria-label="main navigation" :class="{ isShoppingCartOpen }">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://bulma.io">
        <img alt="Vue logo" class="logo" src="@/assets/logo.svg" width="28" height="28" />

      </a>

      <a role="button" class="navbar-burger" :class="{ 'is-active': isActive }" @click="isActive = !isActive" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu" :class="{ 'is-active': isActive }">
      <div class="navbar-start">
        <RouterLink class="navbar-item" to="/" >Home</RouterLink>
        <RouterLink class="navbar-item" to="/about">About</RouterLink>
        <RouterLink class="navbar-item" to="/products">Products</RouterLink>
        
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>

          <div class="navbar-dropdown">
            <a class="navbar-item">
              About
            </a>
            <a class="navbar-item">
              Jobs
            </a>
            <a class="navbar-item">
              Contact
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
              Report an issue
            </a>
          </div>
        </div>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <a class="button" :class="{ 'is-active': isShoppingCartOpen }" @click.prevent="isShoppingCartOpen = !isShoppingCartOpen">
            <span class="icon">
              <i class="fas fa-shopping-cart"></i>
            </span>
            <i class="tag is-danger is-rounded is-small" v-if="cartCount">{{ cartCount }}</i>
          </a>
        </div>
        <div class="navbar-item">
          <LoginBadge />
        </div>
      </div>
    </div>
  </nav>
  <FlyoutPanel  :class="{ 'is-active': isShoppingCartOpen }">
    <ShoppingCart />
  </FlyoutPanel>
</template>


<style scoped>

@media (min-width: 641px) {
  .navbar {
    margin-right: 2rem;
    transition: margin-right 0.5s ease-in-out;
  }
  .navbar.isShoppingCartOpen {
    margin-right: 20rem;
  }
}
.tag.is-small {
  position: absolute;
  transform: translate(50%, -30%);
  font-size: x-small;
}
.router-link-active {
  font-weight: bold;
  border-bottom: 2px solid #00d1b2;
}
</style>

.router-link-active {
  font-weight: bold;
  border-bottom: 2px solid #00d1b2;
}
</style>

// react/components/NavBar.tsx
import { useState } from 'react';
import { NavLink } from 'react-router-dom';
//import LoginBadge from './LoginBadge.vue';
//import FlyoutPanel from './FlyoutPanel.vue';
//import ShoppingCart from './ShoppingCart.vue';
//import { count as cartCount } from "@/model/shoppingCart";

const LoginBadge = () => <div>login</div>;
const FlyoutPanel = ( { children, ...rest } : { children: React.ReactNode, className: string } ) => <div {...rest}>
  { children }
</div>;
const ShoppingCart = () => <div>cart</div>;
const cartCount = 0;

export default function NavBar() {
  const [isActive, setIsActive] = useState(false);
  const [isShoppingCartOpen, setIsShoppingCartOpen] = useState(false);
}

return ( <>
  <nav className={`navbar ${isShoppingCartOpen && "isShoppingCartOpen"}`} role="navigation" aria-label="main navigation">
    <div className="navbar-brand">
      <a className="navbar-item" href="https://bulma.io">
        <img alt="Vue logo" className="logo" src="@/assets/logo.svg" width="28" height="28" />

      </a>

      <a role="button" className={"navbar-burger " + (isActive && 'is-active')} onclick=(()=>) "isActive = !isActive" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" className={"navbar-menu " + (isActive ? 'is-active': '')} >
      <div className="navbar-start">
        <RouterLink className="navbar-item" to="/" >Home</RouterLink>
        <RouterLink className="navbar-item" to="/about">About</RouterLink>
        <RouterLink className="navbar-item" to="/products">Products</RouterLink>
        
        <div className="navbar-item has-dropdown is-hoverable">
          <a className="navbar-link">
            More
          </a>

          <div className="navbar-dropdown">
            <a className="navbar-item">
              About
            </a>
            <a className="navbar-item">
              Jobs
            </a>
            <a className="navbar-item">
              Contact
            </a>
            <hr className="navbar-divider"/>
            <a className="navbar-item">
              Report an issue
            </a>
          </div>
        </div>
      </div>

      <div className="navbar-end">
        <div className="navbar-item">
          <a className={"button " + (isShoppingCartOpen && 'is-active')} click="isShoppingCartOpen = !isShoppingCartOpen">
            <span className="icon">
              <i className="fas fa-shopping-cart"></i>
            </span>
            <i className="tag is-danger is-rounded is-small" v-if="cartCount">{ cartCount }</i>
          </a>
        </div>
        <div className="navbar-item">
          <LoginBadge />
        </div>
      </div>
    </div>
  </nav>
  <FlyoutPanel  className={ isShoppingCartOpen ? 'is-active': ''}>
    <ShoppingCart />
  </FlyoutPanel>
</>)
